services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8094:8002"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
